--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cryotap/Joker
build-by-default: true
branches:
- main
projects:
  Joker:
    path: ""
    icon: "icon.gif"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
...
